### ISSUE TITLE
Document the WAC-Allow header in the spec.

### ISSUE THREAD

**Issue by timbl** [solid/solid-spec#212] opened 2019-08-14 21:38 UTC
This allows client code to be smart about whether to give the user editing interfaces to data or just view interfaces. 

It also allows them to know whether it open to the public, which might affect for example, whether the user is invited to make a public link, like, bookmark, etc of the resource.

**Comment by RubenVerborgh** [comment] 2019-08-14 21:39
A draft is at https://github.com/solid/solid-spec/blob/103b1e027356bd525e4cad0138e8288f4881df39/api-rest.md#wac-allow-headers

**Comment by timbl** [comment] 2019-08-14 21:44
It says "If 'write' is present then 'append' should also be present." but "If write is present, Append is implied" would be more like the ACL spec, I thought.

**Comment by RubenVerborgh** [comment] 2019-08-14 21:45
Agreed. It's not very normative at the moment, an explicit link to ACL should be made.

**Comment by csarven** [comment] 2020-05-05 13:00
Transfering this issue to solid/specification .  For the most part it is a duplicate of https://github.com/solid/specification/issues/170 but keeping it open for the time being.

**Closed by csarven** 2020-05-05 13:00 UTC
